[build]
builder = "NIXPACKS"
buildCommand = "npx nx run website:build:production"
nixpacksPlan = {"providers":["node"]}
watchPatterns = ["/website"]

[deploy]
runtime = "V2"
numReplicas = 1
startCommand = "npx nx run website:serve:production"
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10